"""fix links table

Revision ID: 01f714f24a94
Revises: 9cc4c7583ce6
Create Date: 2026-04-12 18:23:07.756762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f714f24a94'
down_revision: Union[str, Sequence[str], None] = '9cc4c7583ce6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('last_click', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'last_click')
    # ### end Alembic commands ###
